port: 5432

spring:
  datasource:
    url: jdbc:postgresql://walletdb-postgresql-instance.cjlbkgvenvzw.eu-north-1.rds.amazonaws.com:5432/${main-db-name}
    username: ololoev1
    password: ololoev2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        temp:
          use_jdbc_metadata_defaults: false

main-db-name: sanio

#telegram-bot:
#  name: WalletBot
#  token: 5600281255:AAEbHt3A10TfhlWo-cxKgGJqWobjI_R4q7E
telegram-bot:
  name: wallet-demo-bot
  token: 5592588678:AAG37hWFUB_KTfqavmxIa_1zoKBJT9bX6tE

logging:
  level:
    org.hibernate: warn