server:
  port: 5432

spring:
  datasource:
    url: jdbc:postgresql://walletdb-postgresql-instance.cjlbkgvenvzw.eu-north-1.rds.amazonaws.com:5432/${main-db-name}
    username: inputUsernameToRunConfig
    password: inputPasswordToRunConfig
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog-master.yaml

main-db-name: user_AM_walletDB

telegram-bot:
  name: Толька
  token: Булька

logging:
  level:
    org.hibernate: info
    liquibase: info