server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://walletdb-postgresql-instance.cjlbkgvenvzw.eu-north-1.rds.amazonaws.com:5432/${main-db-name}
    username: ば
    password: 場
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog-master.yaml

main-db-name: 所

telegram-bot:
  name: 野
  token: 食

logging:
  level:
    org.hibernate: info
    liquibase: info