port: 5432

spring:
  datasource:
    url: jdbc:postgresql://walletdb-postgresql-instance.cjlbkgvenvzw.eu-north-1.rds.amazonaws.com:5432/${main-db-name}
    username: inputUsernameToRunConfig
    password: inputPasswordToRunConfig
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
   enabled: true
   change-log: classpath:/db/changelog/changelog-master.yaml

main-db-name: user_AM_walletDB

telegram-bot:
  name: WalletBot
  token: 5600281255:AAEbHt3A10TfhlWo-cxKgGJqWobjI_R4q7E

logging:
  level:
    org.hibernate: info
